### ISSUE TITLE
KWh wrong values on my installation (?)

### ISSUE THREAD

**Issue by ctrl-alt-d** [binsentsu/home-assistant-solaredge-modbus#34]
Hi, thanks about this great integration, nice software!

After install this great integration, I can see metrics that are accurate with consumption. For example, solar production:

![Selecció_318](https://user-images.githubusercontent.com/3105983/132382309-7f579436-f7e9-40b8-9ec5-677f9fa6e60d.png)

Also, I can see how many kw I'm getting from grid (-), or I'm sending to grid (+). In this case, I'm getting 130W from grid:

![Selecció_319](https://user-images.githubusercontent.com/3105983/132382434-69bf115f-96b0-48bf-b883-829b4f7e3011.png)

But I can not use this metrics when I configure HA Energy (Maybe because they are on W and not on KWh).

My issue is with the KWh metrics:

Meter, import KWh looks wrong:

![Selecció_321](https://user-images.githubusercontent.com/3105983/132382591-76797b8f-3e4a-450a-8b32-308568f12619.png)

Meter, output KWh looks wrong:

![Selecció_320](https://user-images.githubusercontent.com/3105983/132382595-07b119e2-13b7-4d4d-b753-919942ed2fd8.png)

Then, the dashboard has no sense:

![Selecció_323](https://user-images.githubusercontent.com/3105983/132382796-117b5665-b811-424b-8c8e-23c50eedd3fa.png)

I have opened this issue because I don't know what I'm doing wrong. Maybe someone can help me with HA energy configuration.

Thanks a lot, and sorry about my noob question.

# My config

![Selecció_324](https://user-images.githubusercontent.com/3105983/132387040-c1aca640-4de0-43b8-869e-505813832c39.png)

# Energy panel

Production on panel is wrong:

![Selecció_325](https://user-images.githubusercontent.com/3105983/132387059-6847d8a0-59bf-408d-8cca-f00b8b45ce6f.png)

**Comment by mpredfearn** [comment]
The Meter kWh values are cumulative since the meter was installed. So over the lifetime of your system, you have exported ~567kWh and imported ~155kWh. I can't see "AC Energy" in your screenshots but it is also the cumulative energy your system has produced, so based on the Solaredge portal I would expect that sensor to have a value around 1.17MWh.
You need to look at how much the meter readings change over time (which is what the HA dashboard is doing) to determine the energy flow.
You have your energy dashboard set up exactly as I have, with the same sensors. On the Solaredge portal, you need to look at the energy graphs below the power flows (power is instantaneous, energy is cumulative) and compare it to HAs idea of the energy distribution.

**Comment by ctrl-alt-d** [comment]
thanks @mpredfearn
