### ISSUE TITLE
Issues with energy integration and sensors

### ISSUE THREAD

**Issue by atze09** [binsentsu/home-assistant-solaredge-modbus#74]
Hello i use your integration for a long time and now wanted to integrate it into the energy dashboard of HA.
But i can only make the single phases to be visualized:
![image](https://user-images.githubusercontent.com/6229866/145980668-9b457d56-0029-4e3e-a832-2cafb1821c83.png)

The imported/exported sum's and the PV_AC is not beeing displayed.
![image](https://user-images.githubusercontent.com/6229866/145980961-1961ed05-bcf5-43fc-8382-f44523c7c12d.png)

Maybe anyone can help me out.

**Comment by binsentsu** [comment]
Don't think this is something the integration can control. All kWh sensors have the correct state class and device class, so they are selectable for putting on the dashboard. The fact that they are not visible on the dashboard is out of control of this integration. New sensors take 2 hours before they appear, I assume you took that into account? What happens if you put less sensors on the board (eg. remove a,b,c and only keep the sum)

**Comment by atze09** [comment]
Yes i took that into account, i also tried with less esnsors, but it doesn't work in the current month.
But if i scroll back to August it works with your sensors.
![image](https://user-images.githubusercontent.com/6229866/146140764-72a2de8e-e72d-4cbc-abab-c43258c6b1c6.png)

But in Septembera dn Oktober it showed the same values every day:
![image](https://user-images.githubusercontent.com/6229866/146140843-1583a7d5-48f6-48bd-bc83-fae9ff5d1652.png)

And in November it stopped working,
![image](https://user-images.githubusercontent.com/6229866/146140936-10432883-ef81-4fbf-82e8-e0bab462f915.png)

Maybe it is really caused by HA.
I will check the possibility to reset the HA energy dashboard

**Comment by ChristophCaina** [comment]
not sure - we haven't heard anything back since december last year... this could probably be closed?

**Comment by atze09** [comment]
yes
